module.exports = {
    COMMAND: 'COMMAND',
    LOCATION: 'LOCATION',
    TEXT: 'TEXT',
    PHOTO: 'PHOTO',
    AUDIO: 'AUDIO',
    VIDEO: 'VIDEO',
    ACTION: 'ACTION',
    CONTACT: 'CONTACT',
    STICKER: 'STICKER',
    DOCUMENT: 'DOCUMENT',
    ALL: 'ALL',
    ALWAYS: 'ALWAYS'
};
